create table if not exists public.mehendi_artists (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  public_address text not null check (char_length(public_address) between 2 and 240),
  base_area text not null check (char_length(base_area) between 2 and 120),
  bio text check (bio is null or char_length(bio) <= 1200),
  photo_url text,
  photo_path text,
  active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mehendi_catalog_items (
  id uuid primary key default gen_random_uuid(),
  artist_id uuid not null references public.mehendi_artists(id) on delete restrict,
  title text not null check (char_length(title) between 2 and 160),
  service_type text not null check (service_type in ('Mehendi','Kolka','Mehendi + Kolka')),
  description text check (description is null or char_length(description) <= 1600),
  price numeric(12,2) not null check (price >= 0),
  pricing_unit text not null default 'per_booking' check (pricing_unit in ('per_booking','per_person')),
  duration_minutes integer check (duration_minutes is null or duration_minutes between 15 and 1440),
  image_url text,
  image_path text,
  active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mehendi_travel_zones (
  id bigint generated by default as identity primary key,
  label text not null check (char_length(label) between 2 and 80),
  min_km numeric(6,2) not null check (min_km >= 0),
  max_km numeric(6,2) not null check (max_km > min_km and max_km <= 15),
  fee numeric(12,2) not null check (fee >= 0),
  active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mehendi_addons (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  description text check (description is null or char_length(description) <= 1200),
  price numeric(12,2) not null check (price >= 0),
  unit_label text not null default 'unit' check (char_length(unit_label) between 1 and 40),
  image_url text,
  image_path text,
  active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists mehendi_catalog_items_artist_idx on public.mehendi_catalog_items(artist_id, active, sort_order);
create index if not exists mehendi_artists_public_idx on public.mehendi_artists(active, sort_order);
create index if not exists mehendi_travel_zones_public_idx on public.mehendi_travel_zones(active, sort_order);
create index if not exists mehendi_addons_public_idx on public.mehendi_addons(active, sort_order);

alter table public.mehendi_bookings
  add column if not exists artist_id uuid references public.mehendi_artists(id) on delete set null,
  add column if not exists catalog_item_id uuid references public.mehendi_catalog_items(id) on delete set null,
  add column if not exists travel_zone_id bigint references public.mehendi_travel_zones(id) on delete set null,
  add column if not exists addon_id uuid references public.mehendi_addons(id) on delete set null,
  add column if not exists addon_quantity integer not null default 0 check (addon_quantity between 0 and 100),
  add column if not exists artist_name_snapshot text,
  add column if not exists catalog_item_snapshot text,
  add column if not exists travel_zone_snapshot text,
  add column if not exists addon_snapshot text,
  add column if not exists catalog_base_price numeric(12,2),
  add column if not exists catalog_travel_fee numeric(12,2),
  add column if not exists catalog_addon_price numeric(12,2),
  add column if not exists catalog_total numeric(12,2),
  add column if not exists catalog_pricing_unit text,
  add column if not exists cancellation_acknowledged boolean not null default false,
  add column if not exists payment_status text not null default 'not_requested'
    check (payment_status in ('not_requested','payment_requested','paid','refunded'));

create index if not exists mehendi_bookings_artist_idx on public.mehendi_bookings(artist_id);
create index if not exists mehendi_bookings_catalog_item_idx on public.mehendi_bookings(catalog_item_id);

alter table public.mehendi_artists enable row level security;
alter table public.mehendi_catalog_items enable row level security;
alter table public.mehendi_travel_zones enable row level security;
alter table public.mehendi_addons enable row level security;

revoke all on public.mehendi_artists, public.mehendi_catalog_items, public.mehendi_travel_zones, public.mehendi_addons from anon, authenticated;
grant select on public.mehendi_artists, public.mehendi_catalog_items, public.mehendi_travel_zones, public.mehendi_addons to anon, authenticated;
grant insert, update on public.mehendi_artists, public.mehendi_catalog_items, public.mehendi_travel_zones, public.mehendi_addons to authenticated;
grant usage, select on sequence public.mehendi_travel_zones_id_seq to authenticated;

create policy "Public can read active Mehendi artists" on public.mehendi_artists for select to anon
using (active);
create policy "Owner can manage Mehendi artists" on public.mehendi_artists for all to authenticated
using ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2')
with check ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2');

create policy "Public can read active Mehendi designs" on public.mehendi_catalog_items for select to anon
using (active and exists (select 1 from public.mehendi_artists a where a.id = artist_id and a.active));
create policy "Owner can manage Mehendi designs" on public.mehendi_catalog_items for all to authenticated
using ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2')
with check ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2');

create policy "Public can read active Mehendi travel zones" on public.mehendi_travel_zones for select to anon using (active);
create policy "Owner can manage Mehendi travel zones" on public.mehendi_travel_zones for all to authenticated
using ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2')
with check ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2');

create policy "Public can read active Mehendi add-ons" on public.mehendi_addons for select to anon using (active);
create policy "Owner can manage Mehendi add-ons" on public.mehendi_addons for all to authenticated
using ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2')
with check ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal' = 'aal2');

insert into public.mehendi_travel_zones(label,min_km,max_km,fee,active,sort_order)
select * from (values
  ('০–৫ কিমি',0::numeric,5::numeric,0::numeric,false,1),
  ('৫–১০ কিমি',5::numeric,10::numeric,0::numeric,false,2),
  ('১০–১৫ কিমি',10::numeric,15::numeric,0::numeric,false,3)
) as seed(label,min_km,max_km,fee,active,sort_order)
where not exists (select 1 from public.mehendi_travel_zones);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('mehendi-catalog','mehendi-catalog',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy "Owner can upload Mehendi catalog images" on storage.objects for insert to authenticated
with check (bucket_id='mehendi-catalog' and (select auth.uid())='5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal'='aal2');
create policy "Owner can read Mehendi catalog image records" on storage.objects for select to authenticated
using (bucket_id='mehendi-catalog' and (select auth.uid())='5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal'='aal2');
create policy "Owner can update Mehendi catalog images" on storage.objects for update to authenticated
using (bucket_id='mehendi-catalog' and (select auth.uid())='5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal'='aal2')
with check (bucket_id='mehendi-catalog' and (select auth.uid())='5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal'='aal2');
create policy "Owner can delete Mehendi catalog images" on storage.objects for delete to authenticated
using (bucket_id='mehendi-catalog' and (select auth.uid())='5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt())->>'aal'='aal2');

create or replace function public.create_secure_mehendi_booking(p_booking jsonb)
returns jsonb language plpgsql set search_path to '' as $function$
declare
  v_id bigint; v_existing_id bigint; v_existing_booking_number text; v_paths text[];
  v_event_date date := (p_booking->>'event_date')::date;
  v_preferred_time text := p_booking->>'preferred_time';
  v_client_request_id uuid := nullif(p_booking->>'client_request_id','')::uuid;
begin
  if v_event_date < current_date then raise exception using errcode='P0001',message='EVENT_DATE_IN_PAST'; end if;
  if v_preferred_time not in ('Morning','Afternoon','Evening','Night') then raise exception using errcode='P0001',message='INVALID_TIME_SLOT'; end if;
  if v_client_request_id is not null then
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('mehendi-request|'||v_client_request_id::text,0));
    select id,booking_number into v_existing_id,v_existing_booking_number from public.mehendi_bookings where client_request_id=v_client_request_id limit 1;
    if v_existing_id is not null then return jsonb_build_object('id',v_existing_id,'booking_number',v_existing_booking_number,'reused',true); end if;
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_event_date::text||'|'||v_preferred_time,0));
  if exists(select 1 from public.mehendi_bookings where event_date=v_event_date and preferred_time=v_preferred_time and status in ('Confirmed','Completed')) then
    raise exception using errcode='P0001',message='SLOT_ALREADY_BOOKED';
  end if;
  select coalesce(array_agg(value),'{}'::text[]) into v_paths from jsonb_array_elements_text(coalesce(p_booking->'custom_design_paths','[]'::jsonb));
  insert into public.mehendi_bookings(
    booking_number,client_request_id,customer_name,phone,customer_email,event_date,preferred_time,occasion,service_type,number_of_people,
    venue_area,address,notes,mehendi_coverage,mehendi_side,mehendi_hands,kolka_placement,kolka_side,custom_design_paths,status,
    artist_id,catalog_item_id,travel_zone_id,addon_id,addon_quantity,artist_name_snapshot,catalog_item_snapshot,travel_zone_snapshot,addon_snapshot,
    catalog_base_price,catalog_travel_fee,catalog_addon_price,catalog_total,catalog_pricing_unit,cancellation_acknowledged,payment_status
  ) values (
    p_booking->>'booking_number',v_client_request_id,p_booking->>'customer_name',p_booking->>'phone',nullif(p_booking->>'customer_email',''),v_event_date,v_preferred_time,
    p_booking->>'occasion',p_booking->>'service_type',(p_booking->>'number_of_people')::integer,p_booking->>'venue_area',p_booking->>'address',nullif(p_booking->>'notes',''),
    nullif(p_booking->>'mehendi_coverage',''),nullif(p_booking->>'mehendi_side',''),nullif(p_booking->>'mehendi_hands',''),nullif(p_booking->>'kolka_placement',''),
    nullif(p_booking->>'kolka_side',''),v_paths,'Request Received',nullif(p_booking->>'artist_id','')::uuid,nullif(p_booking->>'catalog_item_id','')::uuid,
    nullif(p_booking->>'travel_zone_id','')::bigint,nullif(p_booking->>'addon_id','')::uuid,coalesce((p_booking->>'addon_quantity')::integer,0),
    nullif(p_booking->>'artist_name_snapshot',''),nullif(p_booking->>'catalog_item_snapshot',''),nullif(p_booking->>'travel_zone_snapshot',''),nullif(p_booking->>'addon_snapshot',''),
    nullif(p_booking->>'catalog_base_price','')::numeric,nullif(p_booking->>'catalog_travel_fee','')::numeric,nullif(p_booking->>'catalog_addon_price','')::numeric,
    nullif(p_booking->>'catalog_total','')::numeric,nullif(p_booking->>'catalog_pricing_unit',''),coalesce((p_booking->>'cancellation_acknowledged')::boolean,false),'not_requested'
  ) returning id into v_id;
  return jsonb_build_object('id',v_id,'booking_number',p_booking->>'booking_number','reused',false);
end;$function$;

revoke all on function public.create_secure_mehendi_booking(jsonb) from public,anon,authenticated;
grant execute on function public.create_secure_mehendi_booking(jsonb) to service_role;

create or replace function public.update_mehendi_booking_status(p_booking_id bigint,p_status text)
returns jsonb language plpgsql set search_path to '' as $function$
declare v_booking public.mehendi_bookings%rowtype; v_slot_key text;
begin
  if p_status not in ('Request Received','Contacted','Confirmed','Completed','Cancelled','Slot Unavailable') then
    raise exception using errcode='P0001',message='INVALID_BOOKING_STATUS';
  end if;
  select * into v_booking from public.mehendi_bookings where id=p_booking_id for update;
  if not found then raise exception using errcode='P0001',message='BOOKING_NOT_FOUND'; end if;
  if v_booking.payment_status='paid' and p_status='Cancelled' then
    raise exception using errcode='P0001',message='PAID_BOOKING_NON_CANCELLABLE';
  end if;
  v_slot_key:=v_booking.event_date::text||'|'||v_booking.preferred_time;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_slot_key,0));
  if p_status='Confirmed' then
    if exists(select 1 from public.mehendi_bookings where event_date=v_booking.event_date and preferred_time=v_booking.preferred_time and status in ('Confirmed','Completed') and id<>p_booking_id) then
      raise exception using errcode='P0001',message='SLOT_ALREADY_BOOKED';
    end if;
    update public.mehendi_bookings set status='Confirmed',updated_at=now() where id=p_booking_id;
    update public.mehendi_bookings set status='Slot Unavailable',updated_at=now() where event_date=v_booking.event_date and preferred_time=v_booking.preferred_time and id<>p_booking_id and status in ('Request Received','Contacted');
  else
    update public.mehendi_bookings set status=p_status,updated_at=now() where id=p_booking_id;
    if v_booking.status in ('Confirmed','Completed') and p_status not in ('Confirmed','Completed') then
      update public.mehendi_bookings set status='Request Received',updated_at=now() where event_date=v_booking.event_date and preferred_time=v_booking.preferred_time and status='Slot Unavailable';
    end if;
  end if;
  select * into v_booking from public.mehendi_bookings where id=p_booking_id;
  return to_jsonb(v_booking);
end;$function$;
