create table if not exists public.agent_tasks (
  id bigint generated by default as identity primary key,
  agent_role text not null check (agent_role in ('operations','content','design','support','analyst')),
  direction text not null check (char_length(direction) between 3 and 2000),
  risk_level text not null default 'low' check (risk_level in ('low','medium','high')),
  status text not null default 'awaiting_start_approval' check (status in (
    'awaiting_start_approval','approved_to_start','in_progress',
    'awaiting_completion_approval','completed','rejected'
  )),
  result_summary text check (result_summary is null or char_length(result_summary) <= 4000),
  created_by uuid not null references auth.users(id),
  start_approved_by uuid references auth.users(id),
  start_approved_at timestamptz,
  started_at timestamptz,
  completion_requested_at timestamptz,
  completion_approved_by uuid references auth.users(id),
  completion_approved_at timestamptz,
  completed_at timestamptz,
  rejected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_start_approval_required check (
    status in ('awaiting_start_approval','rejected')
    or (start_approved_by is not null and start_approved_at is not null)
  ),
  constraint agent_finish_approval_required check (
    status <> 'completed'
    or (completion_approved_by is not null and completion_approved_at is not null and completed_at is not null)
  )
);

alter table public.agent_tasks enable row level security;
revoke all on table public.agent_tasks from anon, authenticated;
grant select, insert, update on table public.agent_tasks to authenticated;
grant usage, select on sequence public.agent_tasks_id_seq to authenticated;

drop policy if exists "Owner can read agent tasks" on public.agent_tasks;
create policy "Owner can read agent tasks" on public.agent_tasks for select to authenticated
using ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt()->>'aal') = 'aal2');

drop policy if exists "Owner can create agent tasks" on public.agent_tasks;
create policy "Owner can create agent tasks" on public.agent_tasks for insert to authenticated
with check (
  (select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid
  and created_by = (select auth.uid())
  and (select auth.jwt()->>'aal') = 'aal2'
);

drop policy if exists "Owner can update agent tasks" on public.agent_tasks;
create policy "Owner can update agent tasks" on public.agent_tasks for update to authenticated
using ((select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid and (select auth.jwt()->>'aal') = 'aal2')
with check (
  (select auth.uid()) = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid
  and created_by = '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid
  and (select auth.jwt()->>'aal') = 'aal2'
);

create or replace function public.enforce_agent_task_approval()
returns trigger language plpgsql security invoker set search_path = public, auth as $$
declare
  owner_id constant uuid := '5beecdb3-5e80-4a35-9133-5fc01ab7a772'::uuid;
  caller_id uuid := auth.uid();
  caller_aal text := auth.jwt()->>'aal';
begin
  if caller_id is distinct from owner_id or caller_aal is distinct from 'aal2' then
    raise exception 'Owner two-step approval is required';
  end if;

  if tg_op = 'INSERT' then
    if new.status <> 'awaiting_start_approval' or new.created_by is distinct from caller_id
       or new.start_approved_by is not null or new.completion_approved_by is not null then
      raise exception 'New tasks must wait for owner start approval';
    end if;
    new.updated_at := now();
    return new;
  end if;

  if new.id is distinct from old.id or new.created_by is distinct from old.created_by
     or new.agent_role is distinct from old.agent_role or new.direction is distinct from old.direction
     or new.risk_level is distinct from old.risk_level or new.created_at is distinct from old.created_at then
    raise exception 'Agent task identity and direction are immutable';
  end if;

  if old.status = 'awaiting_start_approval' and new.status = 'approved_to_start' then
    if new.start_approved_by is distinct from caller_id or new.start_approved_at is null then
      raise exception 'Explicit owner start approval is required';
    end if;
  elsif old.status = 'awaiting_start_approval' and new.status = 'rejected' then
    if new.rejected_at is null then raise exception 'Rejection timestamp is required'; end if;
  elsif old.status = 'approved_to_start' and new.status = 'in_progress' then
    if old.start_approved_by is distinct from caller_id or old.start_approved_at is null or new.started_at is null then
      raise exception 'Task cannot start without owner approval';
    end if;
  elsif old.status = 'in_progress' and new.status = 'awaiting_completion_approval' then
    if new.completion_requested_at is null or nullif(btrim(new.result_summary), '') is null then
      raise exception 'Work summary is required before finish approval';
    end if;
  elsif old.status = 'awaiting_completion_approval' and new.status = 'completed' then
    if new.completion_approved_by is distinct from caller_id or new.completion_approved_at is null or new.completed_at is null then
      raise exception 'Explicit owner finish approval is required';
    end if;
  elsif old.status = 'awaiting_completion_approval' and new.status = 'in_progress' then
    if new.completion_requested_at is not null or new.result_summary is not null then
      raise exception 'Returned work must clear its completion request';
    end if;
  elsif new.status is distinct from old.status then
    raise exception 'Invalid agent task status transition: % to %', old.status, new.status;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.enforce_agent_task_approval() from public, anon, authenticated;
drop trigger if exists agent_task_approval_guard on public.agent_tasks;
create trigger agent_task_approval_guard before insert or update on public.agent_tasks
for each row execute function public.enforce_agent_task_approval();

comment on table public.agent_tasks is
'Owner-controlled agent queue. Separate start and completion approvals are enforced in the database.';
